name: gifski
summary: gifski
description: |
   GIF encoder based on libimagequant (pngquant).
   Squeezes maximum possible quality from the awful
   GIF format. https://gif.ski

version: 0.0.0-gifski-snap-version-override
adopt-info: gifski-snap-version-override

grade: stable
base: core22
confinement: strict

apps:
  gifski:
    command: bin/gifski
    plugs:
    - home
    - removable-media

parts:
  gifski-snap-version-override:
    plugin: nil
    after: [gifski]
    build-packages:
      - git
    override-pull: |
      snapcraftctl set-version $(git -C "$SNAPCRAFT_PART_SRC" describe --tags --always)

  gifski:
    source: https://github.com/ImageOptim/gifski.git
    plugin: rust
    rust-features:
      - video
    build-packages:
      - pkg-config
      - ffmpeg
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libswresample-dev
      - libswscale-dev
      - libclang-dev
    stage-packages:
      - ffmpeg
      - freeglut3 # dep leak from one of ffmpeg dev libs?
      - libglu1-mesa
